services:
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile.app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www/laravel-app
      - ./vendor:/var/www/laravel-app/vendor
    working_dir: /var/www/laravel-app
    networks:
      - bridge
  
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - php-fpm
    networks:
      - bridge

  redis:
    container_name: ${REDIS_HOST}
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    networks:
      - bridge
  
  mysql:
    container_name: ${DB_HOST}
    image: 'mysql:8.4'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - bridge

networks:
  bridge: