services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www/laravel-app
      - ./vendor:/var/www/laravel-app/vendor
    working_dir: /var/www/laravel-app
    networks:
      - bridge
  
  web:
    container_name: web
    image: 'nginx:alpine'
    ports:
      - '80:80'
    volumes:
      - .:/var/www/laravel-app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - bridge

  redis:
    container_name: ${REDIS_HOST}
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    networks:
      - bridge
  
  mysql:
    container_name: ${DB_HOST}
    image: 'mysql:8.4'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - bridge

networks:
  bridge: