services:
  app:
    container_name: app
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV}
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '80:80'
    volumes:
      - .:/var/www/gamewatch
      - ./vendor:/var/www/gamewatch/vendor
    working_dir: /var/www/gamewatch
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/up"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - bridge

  redis:
    container_name: ${REDIS_HOST}
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    networks:
      - bridge
  
  mysql:
    container_name: ${DB_HOST}
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -p${DB_PASSWORD} -e 'SHOW DATABASES;'"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - bridge

networks:
  bridge: