services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/laravel-app
      - /var/www/laravel-app/vendor
    working_dir: /var/www/laravel-app
    networks:
      - bridge
  
  web:
    container_name: web
    image: 'nginx:alpine'
    ports:
      - '80:80'
    volumes:
      - .:/var/www/laravel-app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - bridge
  
  mysql:
    container_name: db
    image: 'mysql:8.4'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - bridge

networks:
  bridge: