services:
  octane:
    container_name: octane
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        APP_ENV: ${APP_ENV}
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/srv/gamewatch
      - ./vendor:/srv/gamewatch/vendor
    working_dir: /srv/gamewatch
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "artisan", "octane:status"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - bridge
  
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    environment:
      - PHP_UPSTREAM_HOST=octane
    ports:
      - '80:80'
    depends_on:
      octane:
        condition: service_healthy
    networks:
      - bridge

  redis:
    container_name: ${REDIS_HOST}
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    networks:
      - bridge
  
  mysql:
    container_name: ${DB_HOST}
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - bridge

networks:
  bridge: