openapi: 3.0.0
info:
  title: 'Laravel App'
  version: 1.0.0
servers:
  -
    url: 'http://laravel-app.local'
paths:
  /up:
    get:
      tags:
        - application
      operationId: babf1c1e7a1e559b1836be5e2e457254
      responses:
        '200':
          description: OK
      security: []
tags:
  -
    name: application
    description: 'health and other application routes'
