name: Tests & Code Sniffer

on:
  workflow_call:

jobs:
  phpunit-phpcs:
    runs-on: ubuntu-latest

    container:
      image: php:8.3-fpm

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping || exit 1" --health-interval 5s --health-timeout 3s --health-retries 3
    
    steps: 
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: apt-get update && apt-get install -y apt-utils curl wget zip git redis-tools

    - name: Install PHP extensions
      run:  |
        docker-php-ext-configure pcntl --enable-pcntl
        docker-php-ext-install pdo pdo_mysql pcntl
        pecl install xdebug redis
        docker-php-ext-enable xdebug redis

    - name: Install Composer
      run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    
    - name: Install Dependencies
      run: |
        composer install --no-interaction
        composer dump-autoload

    - name: Create .env file
      run: |
        cp .env.example .env
        sed -i 's/REDIS_HOST=.*/REDIS_HOST=redis/' .env
        sed -i 's/REDIS_PASSWORD=.*/REDIS_PASSWORD=null/' .env
    
    - name: Generate Key
      run: php artisan key:generate
    
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    
    - name: Run Code Sniffer
      run: composer phpcs

    - name: Check Redis Connectivity
      run: |
        redis-cli -h redis ping
            
    - name: Run Tests
      run: composer test
