name: Application CI

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  tests-n-cs: 
    uses: ./.github/workflows/tests-n-cs.yml
  
  docker-image:
    runs-on: ubuntu-latest
    needs: tests-n-cs

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image (PHP-fpm)
      run: docker build . --file Dockerfile.app --tag laravel-app/php-fpm

    - name: Build Docker image (Nginx)
      run: docker build . --file Dockerfile.nginx --tag laravel-app/nginx

