name: Application CD

on:
  push:
    branches: [ "master" ]

jobs:
  ci: 
    uses: danieltrolezi/laravel-app/.github/workflows/ci.yml@master

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag laravel-app:$(date +%s)
