name: Application CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  tests-n-cs: 
    uses: danieltrolezi/laravel-app/.github/workflows/tests-n-cs.yml@master

  docker-image-ecr:
    runs-on: ubuntu-latest
    needs: tests-n-cs

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Build Docker image (PHP-fpm)
      run: docker build . --file Dockerfile.app --tag ${{ vars.DOCKER_IMAGE_TAG }}/php-fpm

    - name: Build Docker image (Nginx)
      run: docker build . --file Dockerfile.nginx --tag ${{ vars.DOCKER_IMAGE_TAG }}/nginx

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ vars.AWS_REGION }} \
        | docker login --username AWS --password-stdin ${{ vars.ECR_REPOSITORY_URI }}

    - name: Tag Docker images
      run: |
        docker tag ${{ vars.DOCKER_IMAGE_TAG }}/php-fpm:latest ${{ vars.ECR_REPOSITORY_URI }}:latest-php-fpm
        docker tag ${{ vars.DOCKER_IMAGE_TAG }}/nginx:latest ${{ vars.ECR_REPOSITORY_URI }}:latest-nginx

    - name: Push Docker images to ECR
      run: |
        docker push ${{ vars.ECR_REPOSITORY_URI }}:latest-php-fpm
        docker push ${{ vars.ECR_REPOSITORY_URI }}:latest-nginx