name: Application CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  tests-n-cs: 
    uses: danieltrolezi/laravel-app/.github/workflows/tests-n-cs.yml@master

  docker-image:
    runs-on: ubuntu-latest
    needs: tests-n-cs

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ${{ env.DOCKER_IMAGE_TAG }}:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} \
        | docker login --username AWS --password-stdin ${{ env.ECR_REPOSITORY_URI }}

    - name: Tag Docker image
      run: docker tag ${{ env.DOCKER_IMAGE_TAG }}:latest ${{ env.ECR_REPOSITORY_URI }}:latest

    - name: Push Docker image to ECR
      run: docker push ${{ env.ECR_REPOSITORY_URI }}:latest