name: Pull Request CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  tests-n-cs: 
    uses: ./.github/workflows/tests-n-cs.yml
  
  docker-image:
    runs-on: ubuntu-latest
    needs: tests-n-cs

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image (Octane)
      run: docker build . --file Dockerfile --tag app:latest

